---
- name: Install vim
  apt: pkg={{ item }}
  with_items:
    - vim
    - exuberant-ctags
  sudo: yes

- name: Checkout my.vim
  git: repo={{ my_vim_repo }}
       dest={{ my_vim_dir }}
  sudo: no

- name: Install my.vim
  command: make install-plugins
  args:
    chdir: "{{ my_vim_dir }}"
  sudo: no
