---
- name: Add the SublimeText3 PPA
  apt_repository: repo='ppa:webupd8team/sublime-text-3' state=present
  sudo: yes
  tags: ide

- name: Install SublimeText3
  apt: pkg=sublime-text-installer update-cache=yes
  sudo: yes
  tags: ide

