---
- name: Install git
  apt: pkg=git update-cache=yes
  sudo: yes
  tags: git

- name: Set git user.name to {{ git_user_name }}
  command: git config --global --replace-all user.name {{ git_user_name }}
  sudo: no
  tags: git

- name: Set git user.email to {{ git_user_email }}
  command: git config --global --replace-all user.email {{ git_user_email }}
  sudo: no
  tags: git

- name: Set git push.default to {{ git_push_default }}
  command: git config --global push.default {{ git_push_default }}
  sudo: no
  tags: git

- name: Set git core.editor to {{ git_core_editor }}
  command: git config --system core.editor {{ git_core_editor }}
  sudo: yes
  tags: git

